before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./main.go
    id: ssmm
    binary: ssmm
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: ssmm
    builds:
      - ssmm
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

nfpms:
  - id: ssmm
    maintainer: omarahm3 <me@mrg.sh>
    description: manage multiple projects environment variables in SSM Parameter Store
    homepage: https://github.com/omarahm3/ssmm
    license: MIT
    package_name: ssmm
    builds:
      - ssmm
    formats:
      - deb
      - rpm
      - apk

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
